ignored = ["github.com/k0kubun/pp"]

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/chromedp/chromedp"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
